/*
 * libsyd/tao.h
 *
 * libsyd's information on Tao, the Book of the Way
 *
 * Generated from:
 * https://raw.githubusercontent.com/lovingawareness/tao-te-ching/master/Ursula%20K%20Le%20Guin.md
 *
 * Lao Tzu's Tao Te Ching
 * An English Version by Ursula K. Le Guin
 * ISBN: 978-1-59030-744-1
 *
 * Copyright (c) 2021 Ali Polatel <alip@exherbo.org>
 * SPDX-License-Identifier: GPL-2.0-only
 */

#define SYD_TAO_MAX 82
static const char *SYD_TAO[SYD_TAO_MAX];

#include <stdlib.h>
#include <stdbool.h>
#include <syd/syd.h>

static bool syd_tao_init;

const char *syd_tao_rand(void)
{
	if (!syd_tao_init) {
		srand(1984);
		syd_tao_init = true;
	}

	uint8_t pick = rand() % SYD_TAO_MAX;
	return SYD_TAO[pick];
}

const char *syd_tao_pick(uint8_t pick)
{
	return (pick < SYD_TAO_MAX) ? SYD_TAO[pick] : SYD_TAO[0];
}

inline uint8_t syd_tao_max(void)
{
	return SYD_TAO_MAX;
}

static const char *SYD_TAO[SYD_TAO_MAX] = {
"The Way\n"
"\n"
"The Way that can be experienced is not true;\n"
"The world that can be constructed is not real.\n"
"The Way manifests all that happens and may happen;\n"
"The world represents all that exists and may exist.\n"
"To experience without abstraction is to sense the world;\n"
"To experience with abstraction is to know the world.\n"
"These two experiences are indistinguishable;\n"
"Their construction differs but their effect is the same.\n"
"Beyond the gate of experience flows the Way,\n"
"Which is ever greater and more subtle than the world.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Abstraction\n"
"\n"
"When beauty is abstracted\n"
"Then ugliness has been implied;\n"
"When good is abstracted\n"
"Then evil has been implied.\n"
"So alive and dead are abstracted from nature,\n"
"Difficult and easy abstracted from progress,\n"
"Long and short abstracted from contrast,\n"
"High and low abstracted from depth,\n"
"Song and speech abstracted from melody,\n"
"After and before abstracted from sequence.\n"
"The sage experiences without abstraction,\n"
"And accomplishes without action;\n"
"He accepts the ebb and flow of things,\n"
"Nurtures them, but does not own them,\n"
"And lives, but does not dwell.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Without Action\n"
"\n"
"Not praising the worthy prevents contention,\n"
"Not esteeming the valuable prevents theft,\n"
"Not displaying the beautiful prevents desire.\n"
"In this manner the sage governs people:\n"
"Emptying their minds,\n"
"Filling their bellies,\n"
"Weakening their ambitions,\n"
"And strengthening their bones.\n"
"If people lack knowledge and desire\n"
"Then they can not act;\n"
"If no action is taken\n"
"Harmony remains.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Limitless\n"
"\n"
"The Way is a limitless vessel;\n"
"Used by the self, it is not filled by the world;\n"
"It cannot be cut, knotted, dimmed or stilled;\n"
"Its depths are hidden, ubiquitous and eternal;\n"
"I don't know where it comes from;\n"
"It comes before nature.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Nature\n"
"\n"
"Nature is not kind;\n"
"It treats all things impartially.\n"
"The Sage is not kind,\n"
"And treats all people impartially.\n"
"Nature is like a bellows,\n"
"Empty, yet never ceasing its supply.\n"
"The more it moves, the more it yields;\n"
"So the sage draws upon experience\n"
"And cannot be exhausted.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Experience\n"
"\n"
"Experience is a riverbed,\n"
"Its source hidden, forever flowing:\n"
"Its entrance, the root of the world,\n"
"The Way moves within it:\n"
"Draw upon it; it will not run dry.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Complete\n"
"\n"
"Nature is complete because it does not serve itself.\n"
"The sage places himself after and finds himself before,\n"
"Ignores his desire and finds himself content.\n"
"He is complete because he does not serve himself.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Water\n"
"\n"
"The best of man is like water,\n"
"Which benefits all things, and does not contend with them,\n"
"Which flows in places that others disdain,\n"
"Where it is in harmony with the Way.\n"
"So the sage:\n"
"Lives within nature,\n"
"Thinks within the deep,\n"
"Gives within impartiality,\n"
"Speaks within trust,\n"
"Governs within order,\n"
"Crafts within ability,\n"
"Acts within opportunity.\n"
"He does not contend, and none contend against him.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Retire\n"
"\n"
"Fill a cup to its brim and it is easily spilled;\n"
"Temper a sword to its hardest and it is easily broken;\n"
"Amass the greatest treasure and it is easily stolen;\n"
"Claim credit and honour and you easily fall;\n"
"Retire once your purpose is achieved - this is natural.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Harmony\n"
"\n"
"Embracing the Way, you become embraced;\n"
"Breathing gently, you become newborn;\n"
"Clearing your mind, you become clear;\n"
"Nurturing your children, you become impartial;\n"
"Opening your heart, you become accepted;\n"
"Accepting the world, you embrace the Way.\n"
"Bearing and nurturing,\n"
"Creating but not owning,\n"
"Giving without demanding,\n"
"This is harmony.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Tools\n"
"\n"
"Thirty spokes meet at a nave;\n"
"Because of the hole we may use the wheel.\n"
"Clay is moulded into a vessel;\n"
"Because of the hollow we may use the cup.\n"
"Walls are built around a hearth;\n"
"Because of the doors we may use the house.\n"
"Thus tools come from what exists,\n"
"But use from what does not.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Substance\n"
"\n"
"Too much colour blinds the eye,\n"
"Too much music deafens the ear,\n"
"Too much taste dulls the palate,\n"
"Too much play maddens the mind,\n"
"Too much desire tears the heart.\n"
"In this manner the sage cares for people:\n"
"He provides for the belly, not for the senses;\n"
"He ignores abstraction and holds fast to substance.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Self\n"
"\n"
"Both praise and blame cause concern,\n"
"For they bring people hope and fear.\n"
"The object of hope and fear is the self -\n"
"For, without self, to whom may fortune and disaster occur?\n"
"Therefore,\n"
"Who distinguishes himself from the world may be given the world,\n"
"But who regards himself as the world may accept the world.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Mystery\n"
"\n"
"Looked at but cannot be seen - it is beneath form;\n"
"Listened to but cannot be heard - it is beneath sound;\n"
"Held but cannot be touched - it is beneath feeling;\n"
"These depthless things evade definition,\n"
"And blend into a single mystery.\n"
"In its rising there is no light,\n"
"In its falling there is no darkness,\n"
"A continuous thread beyond description,\n"
"Lining what does not exist;\n"
"Its form formless,\n"
"Its image nothing,\n"
"Its name silence;\n"
"Follow it, it has no back,\n"
"Meet it, it has no face.\n"
"Attend the present to deal with the past;\n"
"Thus you grasp the continuity of the Way,\n"
"Which is its essence.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Enlightenment\n"
"\n"
"The enlightened possess understanding\n"
"So profound they can not be understood.\n"
"Because they cannot be understood\n"
"I can only describe their appearance:\n"
"Cautious as one crossing thin ice,\n"
"Undecided as one surrounded by danger,\n"
"Modest as one who is a guest,\n"
"Unbounded as melting ice,\n"
"Genuine as unshaped wood,\n"
"Broad as a valley,\n"
"Seamless as muddy water.\n"
"Who stills the water that the mud may settle,\n"
"Who seeks to stop that he may travel on,\n"
"Who desires less than what may transpire,\n"
"Decays, but will not renew.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Decay and Renewal\n"
"\n"
"Empty the self completely;\n"
"Embrace perfect peace.\n"
"The world will rise and move;\n"
"Watch it return to rest.\n"
"All the flourishing things\n"
"Will return to their source.\n"
"This return is peaceful;\n"
"It is the flow of nature,\n"
"An eternal decay and renewal.\n"
"Accepting this brings enlightenment,\n"
"Ignoring this brings misery.\n"
"Who accepts nature's flow becomes all-cherishing;\n"
"Being all-cherishing he becomes impartial;\n"
"Being impartial he becomes magnanimous;\n"
"Being magnanimous he becomes natural;\n"
"Being natural he becomes one with the Way;\n"
"Being one with the Way he becomes immortal:\n"
"Though his body will decay, the Way will not.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Rulers\n"
"\n"
"The best rulers are scarcely known by their subjects;\n"
"The next best are loved and praised;\n"
"The next are feared;\n"
"The next despised:\n"
"They have no faith in their people,\n"
"And their people become unfaithful to them.\n"
"When the best rulers achieve their purpose\n"
"Their subjects claim the achievement as their own.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Hypocrisy\n"
"\n"
"When the Way is forgotten\n"
"Duty and justice appear;\n"
"Then knowledge and wisdom are born\n"
"Along with hypocrisy.\n"
"When harmonious relationships dissolve\n"
"Then respect and devotion arise;\n"
"When a nation falls to chaos\n"
"Then loyalty and patriotism are born.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Simplify\n"
"\n"
"If we could discard knowledge and wisdom\n"
"Then people would profit a hundredfold;\n"
"If we could discard duty and justice\n"
"Then harmonious relationships would form;\n"
"If we could discard artifice and profit\n"
"Then waste and theft would disappear.\n"
"Yet such remedies treat only symptoms\n"
"And so they are inadequate.\n"
"People need personal remedies:\n"
"Reveal your naked self and embrace your original nature;\n"
"Bind your self-interest and control your ambition;\n"
"Forget your habits and simplify your affairs.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Wandering\n"
"\n"
"What is the difference between assent and denial?\n"
"What is the difference between beautiful and ugly?\n"
"What is the difference between fearsome and afraid?\n"
"The people are merry as if at a magnificent party\n"
"Or playing in the park at springtime,\n"
"But I am tranquil and wandering,\n"
"Like a newborn before it learns to smile,\n"
"Alone, with no true home.\n"
"The people have enough and to spare,\n"
"Where I have nothing,\n"
"And my heart is foolish,\n"
"Muddled and cloudy.\n"
"The people are bright and certain,\n"
"Where I am dim and confused;\n"
"The people are clever and wise,\n"
"Where I am dull and ignorant;\n"
"Aimless as a wave drifting over the sea,\n"
"Attached to nothing.\n"
"The people are busy with purpose,\n"
"Where I am impractical and rough;\n"
"I do not share the peoples' cares\n"
"But I am fed at nature's breast.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Accept\n"
"\n"
"Harmony is only in following the Way.\n"
"The Way is without form or quality,\n"
"But expresses all forms and qualities;\n"
"The Way is hidden and implicate,\n"
"But expresses all of nature;\n"
"The Way is unchanging,\n"
"But expresses all motion.\n"
"Beneath sensation and memory\n"
"The Way is the source of all the world.\n"
"How can I understand the source of the world?\n"
"By accepting.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Home\n"
"\n"
"Accept and you become whole,\n"
"Bend and you straighten,\n"
"Empty and you fill,\n"
"Decay and you renew,\n"
"Want and you acquire,\n"
"Fulfill and you become confused.\n"
"The sage accepts the world\n"
"As the world accepts the Way;\n"
"He does not display himself, so is clearly seen,\n"
"Does not justify himself, so is recognized,\n"
"Does not boast, so is credited,\n"
"Does not pride himself, so endures,\n"
"Does not contend, so none contend against him.\n"
"The ancients said, \"Accept and you become whole\",\n"
"Once whole, the world is as your home.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Words\n"
"\n"
"Nature says only a few words:\n"
"High wind does not last long,\n"
"Nor does heavy rain.\n"
"If nature's words do not last\n"
"Why should those of man?\n"
"Who accepts harmony, becomes harmonious.\n"
"Who accepts loss, becomes lost.\n"
"For who accepts harmony, the Way harmonizes with him,\n"
"And who accepts loss, the Way cannot find.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Indulgence\n"
"\n"
"Straighten yourself and you will not stand steady;\n"
"Display yourself and you will not be clearly seen;\n"
"Justify yourself and you will not be respected;\n"
"Promote yourself and you will not be believed;\n"
"Pride yourself and you will not endure.\n"
"These behaviours are wasteful, indulgent,\n"
"And so they attract disfavour;\n"
"Harmony avoids them.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Beneath Abstraction\n"
"\n"
"There is a mystery,\n"
"Beneath abstraction,\n"
"Silent, depthless,\n"
"Alone, unchanging,\n"
"Ubiquitous and liquid,\n"
"The mother of nature.\n"
"It has no name, but I call it \"the Way\";\n"
"It has no limit, but I call it \"limitless\".\n"
"Being limitless, it flows away forever;\n"
"Flowing away forever, it returns to my self:\n"
"The Way is limitless,\n"
"So nature is limitless,\n"
"So the world is limitless,\n"
"And so I am limitless.\n"
"For I am abstracted from the world,\n"
"The world from nature,\n"
"Nature from the Way,\n"
"And the Way from what is beneath abstraction.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Calm\n"
"\n"
"Gravity is the source of lightness,\n"
"Calm, the master of haste.\n"
"A lone traveller will journey all day, watching over his\n"
"belongings;\n"
"Only safe in his own bed may he lose them in sleep.\n"
"So the captain of a great vessel should not act lightly or hastily.\n"
"Acting lightly, he loses sight of the world,\n"
"Acting hastily, he loses control of himself.\n"
"The captain can not treat his great ship as a small boat;\n"
"Rather than glitter like jade\n"
"He must stand like stone.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Perfection\n"
"\n"
"The perfect traveller leaves no trail to be followed;\n"
"The perfect speaker leaves no question to be answered;\n"
"The perfect accountant leaves no working to be completed;\n"
"The perfect container leaves no lock to be closed;\n"
"The perfect knot leaves no end to be ravelled.\n"
"So the sage nurtures all men\n"
"And abandons no one.\n"
"He accepts everything\n"
"And rejects nothing.\n"
"He attends to the smallest details.\n"
"For the strong must guide the weak;\n"
"The weak are raw material to the strong.\n"
"If the guide is not respected,\n"
"Or the material is not cared for,\n"
"Confusion will result, no matter how clever one is.\n"
"This is the secret of perfection:\n"
"When raw wood is carved, it becomes a tool;\n"
"When a man is employed, he becomes a tool;\n"
"The perfect carpenter leaves no wood to be carved.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Becoming\n"
"\n"
"Using the male, being female,\n"
"Being the entrance of the world,\n"
"You embrace harmony\n"
"And become as a newborn.\n"
"Using strength, being weak,\n"
"Being the root of the world,\n"
"You complete harmony\n"
"And become as unshaped wood.\n"
"Using the light, being dark,\n"
"Being the world,\n"
"You perfect harmony\n"
"And return to the Way.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Ambition\n"
"\n"
"Those who wish to change the world\n"
"According with their desire\n"
"Cannot succeed.\n"
"The world is shaped by the Way;\n"
"It cannot be shaped by the self.\n"
"Trying to change it, you damage it;\n"
"Trying to possess it, you lose it.\n"
"So some will lead, while others follow.\n"
"Some will be warm, others cold\n"
"Some will be strong, others weak.\n"
"Some will get where they are going\n"
"While others fall by the side of the road.\n"
"So the sage will be neither extravagant nor violent.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Violence\n"
"\n"
"Powerful men are well advised not to use violence,\n"
"For violence has a habit of returning;\n"
"Thorns and weeds grow wherever an army goes,\n"
"And lean years follow a great war.\n"
"A general is well advised\n"
"To achieve nothing more than his orders:\n"
"Not to take advantage of his victory.\n"
"Nor to glory, boast or pride himself;\n"
"To do what is dictated by necessity,\n"
"Not by choice.\n"
"For even the strongest force will weaken with time,\n"
"And then its violence will return, and kill it.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Armies\n"
"\n"
"Armies are tools of violence;\n"
"They cause men to hate and fear.\n"
"The sage will not join them.\n"
"His purpose is creation;\n"
"Their purpose is destruction.\n"
"Weapons are tools of violence,\n"
"Not of the sage;\n"
"He uses them only when there is no choice,\n"
"And then calmly, and with tact,\n"
"For he finds no beauty in them.\n"
"Whoever finds beauty in weapons\n"
"Delights in the slaughter of men;\n"
"And who delights in slaughter\n"
"Cannot content himself with peace.\n"
"So slaughters must be mourned\n"
"And conquest celebrated with a funeral.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Shapes\n"
"\n"
"The Way has no true shape,\n"
"And therefore none can control it.\n"
"If a ruler could control the Way\n"
"All things would follow\n"
"In harmony with his desire,\n"
"And sweet rain would fall,\n"
"Effortlessly slaking every thirst.\n"
"The Way is shaped by use,\n"
"But then the shape is lost.\n"
"Do not hold fast to shapes\n"
"But let sensation flow into the world\n"
"As a river courses down to the sea.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Virtues\n"
"\n"
"Who understands the world is learned;\n"
"Who understands the self is enlightened.\n"
"Who conquers the world has strength;\n"
"Who conquers the self has harmony;\n"
"Who is determined has purpose.\n"
"Who is contented has wealth;\n"
"Who defends his home may long endure;\n"
"Who surrenders his home may long survive it.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Control\n"
"\n"
"The Way flows and ebbs, creating and destroying,\n"
"Implementing all the world, attending to the tiniest details,\n"
"Claiming nothing in return.\n"
"It nurtures all things,\n"
"Though it does not control them;\n"
"It has no intention,\n"
"So it seems inconsequential.\n"
"It is the substance of all things;\n"
"Though it does not control them;\n"
"It has no exception,\n"
"So it seems all-important.\n"
"The sage would not control the world;\n"
"He is in harmony with the world.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Peace\n"
"\n"
"If you offer music and food\n"
"Strangers may stop with you;\n"
"But if you accord with the Way\n"
"All the people of the world will keep you\n"
"In safety, health, community, and peace.\n"
"The Way lacks art and flavour;\n"
"It can neither be seen nor heard,\n"
"But its benefit cannot be exhausted.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Opposition\n"
"\n"
"To reduce someone's influence, first expand it;\n"
"To reduce someone's force, first increase it;\n"
"To overthrow someone, first exalt them;\n"
"To take from someone, first give to them.\n"
"This is the subtlety by which the weak overcome the strong:\n"
"Fish should not leave their depths,\n"
"And swords should not leave their scabbards.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Tranquillity\n"
"\n"
"The Way takes no action, but leaves nothing undone.\n"
"When you accept this\n"
"The world will flourish,\n"
"In harmony with nature.\n"
"Nature does not possess desire;\n"
"Without desire, the heart becomes quiet;\n"
"In this manner the whole world is made tranquil.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Ritual\n"
"\n"
"Well established hierarchies are not easily uprooted;\n"
"Closely held beliefs are not easily released;\n"
"So ritual enthralls generation after generation.\n"
"Harmony does not care for harmony, and so is naturally attained;\n"
"But ritual is intent upon harmony, and so can not attain it.\n"
"Harmony neither acts nor reasons;\n"
"Love acts, but without reason;\n"
"Justice acts to serve reason;\n"
"But ritual acts to enforce reason.\n"
"When the Way is lost, there remains harmony;\n"
"When harmony is lost, there remains love;\n"
"When love is lost, there remains justice;\n"
"And when justice is lost, there remains ritual.\n"
"Ritual is the end of compassion and honesty,\n"
"The beginning of confusion;\n"
"Belief is a colourful hope or fear,\n"
"The beginning of folly.\n"
"The sage goes by harmony, not by hope;\n"
"He dwells in the fruit, not the flower;\n"
"He accepts substance, and ignores abstraction.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Support\n"
"\n"
"In mythical times all things were whole:\n"
"All the sky was clear,\n"
"All the earth was stable,\n"
"All the mountains were firm,\n"
"All the riverbeds were full,\n"
"All of nature was fertile,\n"
"And all the rulers were supported.\n"
"But, losing clarity, the sky tore;\n"
"Losing stability, the earth split;\n"
"Losing strength, the mountains sank;\n"
"Losing water, the riverbeds cracked;\n"
"Losing fertility, nature disappeared;\n"
"And losing support, the rulers fell.\n"
"Rulers depend upon their subjects,\n"
"The noble depend upon the humble;\n"
"So rulers call themselves orphaned, hungry and alone,\n"
"To win the people's support.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Motion and Use\n"
"\n"
"The motion of the Way is to return;\n"
"The use of the Way is to accept;\n"
"All things come from the Way,\n"
"And the Way comes from nothing.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Following\n"
"\n"
"When the great man learns the Way, he follows it with diligence;\n"
"When the common man learns the Way, he follows it on occasion;\n"
"When the mean man learns the Way, he laughs out loud;\n"
"Those who do not laugh, do not learn at all.\n"
"Therefore it is said:\n"
"Who understands the Way seems foolish;\n"
"Who progresses on the Way seems to fail;\n"
"Who follows the Way seems to wander.\n"
"For the finest harmony appears plain;\n"
"The brightest truth appears coloured;\n"
"The richest character appears incomplete;\n"
"The bravest heart appears meek;\n"
"The simplest nature appears inconstant.\n"
"The square, perfected, has no corner;\n"
"Music, perfected, has no melody;\n"
"Love, perfected, has no climax;\n"
"Art, perfected, has no meaning.\n"
"The Way can be neither sensed nor known:\n"
"It transmits sensation and transcends knowledge.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Mind\n"
"\n"
"The Way bears sensation,\n"
"Sensation bears memory,\n"
"Sensation and memory bear abstraction,\n"
"And abstraction bears all the world;\n"
"Each thing in the world bears feeling and doing,\n"
"And, imbued with mind, harmony with the Way.\n"
"As others have taught, so do I teach,\n"
"\"Who loses harmony opposes nature\";\n"
"This is the root of my teaching.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Overcoming\n"
"\n"
"Water overcomes the stone;\n"
"Without substance it requires no opening;\n"
"This is the benefit of taking no action.\n"
"Yet benefit without action,\n"
"And experience without abstraction,\n"
"Are practiced by very few.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Contentment\n"
"\n"
"Health or reputation: which is held dearer?\n"
"Health or possessions: which has more worth?\n"
"Profit or loss: which is more troublesome?\n"
"Great love incurs great expense,\n"
"And great wealth incurs great fear,\n"
"But contentment comes at no cost.\n"
"For who knows when to stop\n"
"Does not continue into danger,\n"
"And so may long endure.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Quiet\n"
"\n"
"Great perfection seems incomplete,\n"
"But does not decay;\n"
"Great abundance seems empty,\n"
"But does not fail.\n"
"Great truth seems contradictory;\n"
"Great cleverness seems stupid;\n"
"Great eloquence seems awkward.\n"
"As spring overcomes the cold,\n"
"And autumn overcomes the heat,\n"
"So calm and quiet overcome the world.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Horses\n"
"\n"
"When a nation follows the Way,\n"
"Horses bear manure through its fields;\n"
"When a nation ignores the Way,\n"
"Horses bear soldiers through its streets.\n"
"There is no greater mistake than following desire;\n"
"There is no greater disaster than forgetting contentment;\n"
"There is no greater sickness than seeking attainment;\n"
"But one who is content to satisfy his needs\n"
"Finds that contentment endures.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Knowing\n"
"\n"
"Without taking a step outdoors\n"
"You know the whole world;\n"
"Without taking a peep out the window\n"
"You know the colour of the sky.\n"
"The more you experience,\n"
"The less you know.\n"
"The sage wanders without knowing,\n"
"Looks without seeing,\n"
"Accomplishes without acting.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Inaction\n"
"\n"
"The follower of knowledge learns as much as he can every day;\n"
"The follower of the Way forgets as much as he can every day.\n"
"By attrition he reaches a state of inaction\n"
"Wherein he does nothing, but nothing remains undone.\n"
"To conquer the world, accomplish nothing;\n"
"If you must accomplish something,\n"
"The world remains beyond conquest.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"People\n"
"\n"
"The sage does not distinguish between himself and the world;\n"
"The needs of other people are as his own.\n"
"He is good to those who are good;\n"
"He is also good to those who are not good,\n"
"Thereby he is good.\n"
"He trusts those who are trustworthy;\n"
"He also trusts those who are not trustworthy,\n"
"Thereby he is trustworthy.\n"
"The sage lives in harmony with the world,\n"
"And his mind is the world's mind.\n"
"So he nurtures the worlds of others\n"
"As a mother does her children.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Death\n"
"\n"
"Men flow into life, and ebb into death.\n"
"Some are filled with life;\n"
"Some are empty with death;\n"
"Some hold fast to life, and thereby perish,\n"
"For life is an abstraction.\n"
"Those who are filled with life\n"
"Need not fear tigers and rhinos in the wilds,\n"
"Nor wear armour and shields in battle;\n"
"The rhinoceros finds no place in them for its horn,\n"
"The tiger no place for its claw,\n"
"The soldier no place for a weapon,\n"
"For death finds no place in them.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Nurture\n"
"\n"
"The Way bears all things;\n"
"Harmony nurtures them;\n"
"Nature shapes them;\n"
"Use completes them.\n"
"Each follows the Way and honours harmony,\n"
"Not by law,\n"
"But by being.\n"
"The Way bears, nurtures, shapes, completes,\n"
"Shelters, comforts, and makes a home for them.\n"
"Bearing without possessing,\n"
"Nurturing without taming,\n"
"Shaping without forcing,\n"
"This is harmony.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Clarity\n"
"\n"
"The origin of the world is its mother;\n"
"Understand the mother, and you understand the child;\n"
"Embrace the child, and you embrace the mother,\n"
"Who will not perish when you die.\n"
"Reserve your judgments and words\n"
"And you maintain your influence;\n"
"Speak your mind and take positions\n"
"And nothing will save you.\n"
"As observing detail is clarity,\n"
"So maintaining flexibility is strength;\n"
"Use the light but shed no light,\n"
"So that you do yourself no harm,\n"
"But embrace clarity.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Difficult Paths\n"
"\n"
"With but a small understanding\n"
"One may follow the Way like a main road,\n"
"Fearing only to leave it;\n"
"Following a main road is easy,\n"
"Yet people delight in difficult paths.\n"
"When palaces are kept up\n"
"Fields are left to weeds\n"
"And granaries empty;\n"
"Wearing fine clothes,\n"
"Bearing sharp swords,\n"
"Glutting with food and drink,\n"
"Hoarding wealth and possessions -\n"
"These are the ways of theft,\n"
"And far from the Way.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Cultivate Harmony\n"
"\n"
"Cultivate harmony within yourself, and harmony becomes real;\n"
"Cultivate harmony within your family, and harmony becomes fertile;\n"
"Cultivate harmony within your community, and harmony becomes\n"
"abundant;\n"
"Cultivate harmony within your culture, and harmony becomes\n"
"enduring;\n"
"Cultivate harmony within the world, and harmony becomes ubiquitous.\n"
"Live with a person to understand that person;\n"
"Live with a family to understand that family;\n"
"Live with a community to understand that community;\n"
"Live with a culture to understand that culture;\n"
"Live with the world to understand the world.\n"
"How can I live with the world?\n"
"By accepting.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Soft Bones\n"
"\n"
"Who is filled with harmony is like a newborn.\n"
"Wasps and snakes will not bite him;\n"
"Hawks and tigers will not claw him.\n"
"His bones are soft yet his grasp is sure,\n"
"For his flesh is supple;\n"
"His mind is innocent yet his body is virile,\n"
"For his vigour is plentiful;\n"
"His song is long-lasting yet his voice is sweet,\n"
"For his grace is perfect.\n"
"But knowing harmony creates abstraction,\n"
"And following abstraction creates ritual.\n"
"Exceeding nature creates calamity,\n"
"And controlling nature creates violence.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Impartiality\n"
"\n"
"Who understands does not preach;\n"
"Who preaches does not understand.\n"
"Reserve your judgments and words;\n"
"Smooth differences and forgive disagreements;\n"
"Dull your wit and simplify your purpose;\n"
"Accept the world.\n"
"Then,\n"
"Friendship and enmity,\n"
"Profit and loss,\n"
"Honour and disgrace,\n"
"Will not affect you;\n"
"The world will accept you.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Conquer with Inaction\n"
"\n"
"Do not control the people with laws,\n"
"Nor violence nor espionage,\n"
"But conquer them with inaction.\n"
"For:\n"
"The more morals and taboos there are,\n"
"The more cruelty afflicts people;\n"
"The more guns and knives there are,\n"
"The more factions divide people;\n"
"The more arts and skills there are,\n"
"The more change obsoletes people;\n"
"The more laws and taxes there are,\n"
"The more theft corrupts people.\n"
"Yet take no action, and the people nurture eachother;\n"
"Make no laws, and the people deal fairly with eachother;\n"
"Own no interest, and the people cooperate with eachother;\n"
"Express no desire, and the people harmonize with eachother.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"No End\n"
"\n"
"When government is lazy and informal\n"
"The people are kind and honest;\n"
"When government is efficient and severe\n"
"The people are discontented and deceitful.\n"
"Good fortune follows upon disaster;\n"
"Disaster lurks within good fortune;\n"
"Who can say how things will end?\n"
"Perhaps there is no end.\n"
"Honesty is ever deceived;\n"
"Kindness is ever seduced;\n"
"Men have been like this for a long time.\n"
"So the sage is firm but not cutting,\n"
"Pointed but not piercing,\n"
"Straight but not rigid,\n"
"Bright but not blinding.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Restraint\n"
"\n"
"Manage a great nation as you would cook a delicate fish.\n"
"To govern men in accord with nature\n"
"It is best to be restrained;\n"
"Restraint makes agreement easy to attain,\n"
"And easy agreement builds harmonious relationships;\n"
"With sufficient harmony no resistance will arise;\n"
"When no resistance arises, then you possess the heart of the\n"
"nation,\n"
"And when you possess the nation's heart, your influence will long\n"
"endure:\n"
"Deeply rooted and firmly established.\n"
"This is the method of far sight and long life.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Demons\n"
"\n"
"When you use the Way to conquer the world,\n"
"Your demons will lose their power to harm.\n"
"It is not that they lose their power as such,\n"
"But that they will not harm others;\n"
"Because they will not harm others,\n"
"You will not harm others:\n"
"When neither you nor your demons can do harm,\n"
"You will be at peace with them.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Submission\n"
"\n"
"A nation is like a hierarchy, a marketplace, and a maiden.\n"
"A maiden wins her husband by submitting to his advances;\n"
"Submission is a means of union.\n"
"So when a large country submits to a small country\n"
"It will adopt the small country;\n"
"When a small country submits to a large country\n"
"It will be adopted by the large country;\n"
"The one submits and adopts;\n"
"The other submits and is adopted.\n"
"It is in the interest of a large country to unite and gain service,\n"
"And in the interest of a small country to unite and gain patronage;\n"
"If both would serve their interests,\n"
"Both must submit.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Sin\n"
"\n"
"The Way is the fate of men,\n"
"The treasure of the saint,\n"
"And the refuge of the sinner.\n"
"Fine words are often borrowed,\n"
"And great deeds are often appropriated;\n"
"Therefore, when a man falls, do not abandon him,\n"
"And when a man gains power, do not honour him;\n"
"Only remain impartial and show him the Way.\n"
"Why should someone appreciate the Way?\n"
"The ancients said, \"By it, those who seek may easily find,\n"
"And those who regret may easily absolve\"\n"
"So it is the most precious gift.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Difficulty\n"
"\n"
"Practice no-action;\n"
"Attend to do-nothing;\n"
"Taste the flavorless,\n"
"Magnify the small,\n"
"Multiply the few,\n"
"Return love for hate.\n"
"Deal with the difficult while it is yet easy;\n"
"Deal with the great while it is yet small;\n"
"The difficult develops naturally from the easy,\n"
"And the great from the small;\n"
"So the sage, by dealing with the small,\n"
"Achieves the great.\n"
"Who finds it easy to promise finds it hard to be trusted;\n"
"Who takes things lightly finds things difficult;\n"
"The sage recognizes difficulty, and so has none.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Care at the Beginning\n"
"\n"
"What lies still is easy to grasp;\n"
"What lies far off is easy to anticipate;\n"
"What is brittle is easy to shatter;\n"
"What is small is easy to disperse.\n"
"Yet a tree broader than a man can embrace is born of a tiny shoot;\n"
"A dam greater than a river can overflow starts with a clod of\n"
"earth;\n"
"A journey of a thousand miles begins at the spot under one's feet.\n"
"Therefore deal with things before they happen;\n"
"Create order before there is confusion.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Care at the End\n"
"\n"
"He who acts, spoils;\n"
"He who grasps, loses.\n"
"People often fail on the verge of success;\n"
"Take care at the end as at the beginning,\n"
"So that you may avoid failure.\n"
"The sage desires no-desire,\n"
"Values no-value,\n"
"Learns no-learning,\n"
"And returns to the places that people have forgotten;\n"
"He would help all people to become natural,\n"
"But then he would not be natural.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Subtlety\n"
"\n"
"The ancients did not seek to rule people with knowledge,\n"
"But to help them become natural.\n"
"It is difficult for knowledgeable people to become natural.\n"
"To use law to control a nation weakens the nation.\n"
"But to use nature to control a nation strengthens the nation.\n"
"Understanding these two paths is understanding subtlety;\n"
"Subtlety runs deep, ranges wide,\n"
"Resolves confusion and preserves peace.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Lead by Following\n"
"\n"
"The river carves out the valley by flowing beneath it.\n"
"Thereby the river is the master of the valley.\n"
"In order to master people\n"
"One must speak as their servant;\n"
"In order to lead people\n"
"One must follow them.\n"
"So when the sage rises above the people,\n"
"They do not feel oppressed;\n"
"And when the sage stands before the people,\n"
"They do not feel hindered.\n"
"So the popularity of the sage does not fail,\n"
"He does not contend, and no one contends against him.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Unimportance\n"
"\n"
"All the world says,\n"
"\"I am important;\n"
"I am separate from all the world.\n"
"I am important because I am separate,\n"
"Were I the same, I could never be important.\"\n"
"Yet here are three treasures\n"
"That I cherish and commend to you:\n"
"The first is compassion,\n"
"By which one finds courage.\n"
"The second is restraint,\n"
"By which one finds strength.\n"
"And the third is unimportance,\n"
"By which one finds influence.\n"
"Those who are fearless, but without compassion,\n"
"Powerful, but without restraint,\n"
"Or influential, yet important,\n"
"Cannot endure.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Compassion\n"
"\n"
"Compassion is the finest weapon and best defence.\n"
"If you would establish harmony,\n"
"Compassion must surround you like a fortress.\n"
"Therefore,\n"
"A good soldier does not inspire fear;\n"
"A good fighter does not display aggression;\n"
"A good conqueror does not engage in battle;\n"
"A good leader does not exercise authority.\n"
"This is the value of unimportance;\n"
"This is how to win the cooperation of others;\n"
"This to how to build the same harmony that is in nature.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Ambush\n"
"\n"
"There is a saying among soldiers:\n"
"It is easier to lose a yard than take an inch.\n"
"In this manner one may deploy troops without marshalling them,\n"
"Bring weapons to bear without exposing them,\n"
"Engage the foe without invading them,\n"
"And exhaust their strength without fighting them.\n"
"There is no worse disaster than misunderstanding your enemy;\n"
"To do so endangers all of my treasures;\n"
"So when two well matched forces oppose eachother,\n"
"The general who maintains compassion will win.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Individuality\n"
"\n"
"My words are easy to understand\n"
"And my actions are easy to perform\n"
"Yet no other can understand or perform them.\n"
"My words have meaning; my actions have reason;\n"
"Yet these cannot be known and I cannot be known.\n"
"We are each unique, and therefore valuable;\n"
"Though the sage wears coarse clothes, his heart is jade.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Limitation\n"
"\n"
"Who recognizes his limitations is healthy;\n"
"Who ignores his limitations is sick.\n"
"The sage recognizes this sickness as a limitation.\n"
"And so becomes immune.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Revolution\n"
"\n"
"When people have nothing more to lose,\n"
"Then revolution will result.\n"
"Do not take away their lands,\n"
"And do not destroy their livelihoods;\n"
"If your burden is not heavy then they will not shirk it.\n"
"The sage maintains himself but exacts no tribute,\n"
"Values himself but requires no honours;\n"
"He ignores abstraction and accepts substance.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Fate\n"
"\n"
"Who is brave and bold will perish;\n"
"Who is brave and subtle will benefit.\n"
"The subtle profit where the bold perish\n"
"For Fate does not honour daring.\n"
"And even the sage dares not tempt fate.\n"
"Fate does not attack, yet all things are conquered by it;\n"
"It does not ask, yet all things answer to it;\n"
"It does not call, yet all things meet it;\n"
"It does not plan, yet all things are determined by it.\n"
"Fate's net is vast and its mesh is coarse,\n"
"Yet none escape it.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Execution\n"
"\n"
"If people were not afraid of death,\n"
"Then what would be the use of an executioner?\n"
"If people were only afraid of death,\n"
"And you executed everyone who did not obey,\n"
"No one would dare to disobey you.\n"
"Then what would be the use of an executioner?\n"
"People fear death because death is an instrument of fate.\n"
"When people are killed by execution rather than by fate,\n"
"This is like carving wood in the place of a carpenter.\n"
"Those who carve wood in place of a carpenter\n"
"Often injure their hands.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Rebellion\n"
"\n"
"When rulers take grain so that they may feast,\n"
"Their people become hungry;\n"
"When rulers take action to serve their own interests,\n"
"Their people become rebellious;\n"
"When rulers take lives so that their own lives are maintained,\n"
"Their people no longer fear death.\n"
"When people act without regard for their own lives\n"
"They overcome those who value only their own lives.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Flexibility\n"
"\n"
"A newborn is soft and tender,\n"
"A crone, hard and stiff.\n"
"Plants and animals, in life, are supple and succulent;\n"
"In death, withered and dry.\n"
"So softness and tenderness are attributes of life,\n"
"And hardness and stiffness, attributes of death.\n"
"Just as a sapless tree will split and decay\n"
"So an inflexible force will meet defeat;\n"
"The hard and mighty lie beneath the ground\n"
"While the tender and weak dance on the breeze above.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Need\n"
"\n"
"Is the action of nature not unlike drawing a bow?\n"
"What is higher is pulled down, and what is lower is raised up;\n"
"What is taller is shortened, and what is thinner is broadened;\n"
"Nature's motion decreases those who have more than they need\n"
"And increases those who need more than they have.\n"
"It is not so with Man.\n"
"Man decreases those who need more than they have\n"
"And increases those who have more than they need.\n"
"To give away what you do not need is to follow the Way.\n"
"So the sage gives without expectation,\n"
"Accomplishes without claiming credit,\n"
"And has no desire for ostentation.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Yielding\n"
"\n"
"Nothing in the world is as soft and yielding as water,\n"
"Yet nothing can better overcome the hard and strong,\n"
"For they can neither control nor do away with it.\n"
"The soft overcomes the hard,\n"
"The yielding overcomes the strong;\n"
"Every person knows this,\n"
"But no one can practice it.\n"
"Who attends to the people would control the land and grain;\n"
"Who attends to the state would control the whole world;\n"
"Truth is easily hidden by rhetoric.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Reconciliation\n"
"\n"
"When conflict is reconciled, some hard feelings remain;\n"
"This is dangerous.\n"
"The sage accepts less than is due\n"
"And does not blame or punish;\n"
"For harmony seeks agreement\n"
"Where justice seeks payment.\n"
"The ancients said: \"nature is impartial;\n"
"Therefore it serves those who serve all.\"\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"Utopia\n"
"\n"
"Let your community be small, with only a few people;\n"
"Keep tools in abundance, but do not depend upon them;\n"
"Appreciate your life and be content with your home;\n"
"Sail boats and ride horses, but don't go too far;\n"
"Keep weapons and armour, but do not employ them;\n"
"Let everyone read and write,\n"
"Eat well and make beautiful things.\n"
"Live peacefully and delight in your own society;\n"
"Dwell within cock-crow of your neighbours,\n"
"But maintain your independence from them.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
,

"The Sage\n"
"\n"
"Honest people use no rhetoric;\n"
"Rhetoric is not honesty.\n"
"Enlightened people are not cultured;\n"
"Culture is not enlightenment.\n"
"Content people are not wealthy;\n"
"Wealth is not contentment.\n"
"So the sage does not serve himself;\n"
"The more he does for others, the more he is satisfied;\n"
"The more he gives, the more he receives.\n"
"Nature flourishes at the expense of no one;\n"
"So the sage benefits all men and contends with none.\n"
"		-- Lao Tse, \"Tao Te Ching\"\n"
};
