/*
 * sydbox/HELPME.h
 * Ask People for Help.
 * Thank you in advance for the Help.
 *
 * See:
 *	https://pink.exherbo.org/
 *	https://sydbox.exherbo.org/
 *	https://pandora.exherbo.org/
 *	https://todo.sr.ht/~alip/sydbox
 *
 * Copyright (c) 2021 Ⓐlï P☮latel <alip@exherbo.org>
 * SPDX-License-Identifier: GPL-2.0-only
 */

#ifndef HELPME_H
# define HELPME_H 1

#define SYD_WARN	"[01;35m"
#define SYD_RESET	"[00;00m"

#define SYD_HELPME \
SYD_WARN"\
Hey y☮u, ☮ut there bey☮nd the wⒶll,\n\
BreⒶking b☮ttles in the hⒶll,\n\
CⒶn y☮u help me?\n\
"SYD_RESET"\n\
Y☮u mⒶy view the Sydb☮x bl☮g\t@\thttps://pink.exherbo.org/\n\
Y☮u mⒶy view the Syd(1) mⒶnuⒶl pⒶge @\thttps://sydbox.exherbo.org/\n\
Y☮u mⒶy view Pand☮ra's pr☮ject pⒶge @\thttps://pandora.exherbo.org/\n\
Send bug rep☮rts t☮\t\t\thttps://todo.sr.ht/~alip/sydbox \n\
ⒶttⒶching p☮ems enc☮urⒶges c☮nsiderⒶti☮n tremend☮usly.\n\
\n\
Copyright (c) 2010, 2011, 2012, 2013, 2014, 2015, 2018, 2020, 2021 Ⓐlï P☮latel <alip@exherbo.org>\n\
SPDX-License-Identifier: GPL-2.0-only\n"

/*
 * Include generated configuration
 * generated by Ⓐutot☮☮ls.
 */
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#endif /* !HELPME_H */
