/*
 * Copyright (c) 2021 Ali Polatel <alip@exherbo.org>
 * All rights reserved.
 * SPDX-License-Identifier: GPL-2.0-only
 */


#ifndef SYD_GUARD_RS_H
#define SYD_GUARD_RS_H

#pragma once

/* Generated with cbindgen:0.19.0 */

#if 0
# *********************************************************
# THIS IS A GENERATED FILE! DO NOT EDIT THIS FILE DIRECTLY!
# *********************************************************
#
#endif


#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdlib.h>
#include <seccomp.h>
#include <unistd.h>
#include "syd/compiler.h"

#if 0
#endif

#endif /* SYD_GUARD_RS_H */
