#ifndef SYD_SYSCALL_OPEN_H
#define SYD_SYSCALL_OPEN_H 1

#include <fcntl.h>

#define OPEN_READONLY_FLAG_MAX 91
static const int open_readonly_flags[OPEN_READONLY_FLAG_MAX] = {
	O_RDONLY,
O_RDONLY|O_CLOEXEC,
O_RDONLY|O_LARGEFILE,
O_RDONLY|O_CLOEXEC|O_PATH,
O_RDONLY|O_LARGEFILE|O_PATH,
O_RDONLY|O_CLOEXEC|O_DIRECTORY,
O_RDONLY|O_LARGEFILE|O_DIRECTORY,
#ifdef O_EXCL
	O_RDONLY|O_EXCL,
#endif
#ifdef O_SYNC
	O_RDONLY|O_SYNC,
#endif
#ifdef O_ASYNC
	O_RDONLY|O_ASYNC,
#endif
#ifdef O_DSYNC
	O_RDONLY|O_DSYNC,
#endif
#ifdef O_APPEND
	O_RDONLY|O_APPEND,
#endif
#ifdef O_DIRECT
	O_RDONLY|O_DIRECT,
#endif
#ifdef O_NOCTTY
	O_RDONLY|O_NOCTTY,
#endif
#ifdef O_CLOEXEC
	O_RDONLY|O_CLOEXEC,
#endif
#ifdef O_NOATIME
	O_RDONLY|O_NOATIME,
#endif
#ifdef O_NOFOLLOW
	O_RDONLY|O_NOFOLLOW,
#endif
#ifdef O_NONBLOCK
	O_RDONLY|O_NONBLOCK,
#endif
#ifdef O_EXCL
	O_RDONLY|O_CLOEXEC|O_EXCL,
#endif
#ifdef O_LARGEFILE
	O_RDONLY|O_LARGEFILE,
#endif
#ifdef O_SYNC
	O_RDONLY|O_CLOEXEC|O_SYNC,
#endif
#ifdef O_ASYNC
	O_RDONLY|O_CLOEXEC|O_ASYNC,
#endif
#ifdef O_DSYNC
	O_RDONLY|O_CLOEXEC|O_DSYNC,
#endif
#ifdef O_EXCL
	O_RDONLY|O_LARGEFILE|O_EXCL,
#endif
#ifdef O_SYNC
	O_RDONLY|O_LARGEFILE|O_SYNC,
#endif
#ifdef O_APPEND
	O_RDONLY|O_CLOEXEC|O_APPEND,
#endif
#ifdef O_ASYNC
	O_RDONLY|O_LARGEFILE|O_ASYNC,
#endif
#ifdef O_DIRECT
	O_RDONLY|O_CLOEXEC|O_DIRECT,
#endif
#ifdef O_DSYNC
	O_RDONLY|O_LARGEFILE|O_DSYNC,
#endif
#ifdef O_NOCTTY
	O_RDONLY|O_CLOEXEC|O_NOCTTY,
#endif
#ifdef O_APPEND
	O_RDONLY|O_LARGEFILE|O_APPEND,
#endif
#ifdef O_CLOEXEC
	O_RDONLY|O_CLOEXEC|O_CLOEXEC,
#endif
#ifdef O_DIRECT
	O_RDONLY|O_LARGEFILE|O_DIRECT,
#endif
#ifdef O_NOATIME
	O_RDONLY|O_CLOEXEC|O_NOATIME,
#endif
#ifdef O_NOCTTY
	O_RDONLY|O_LARGEFILE|O_NOCTTY,
#endif
#ifdef O_EXCL
	O_RDONLY|O_CLOEXEC|O_PATH|O_EXCL,
#endif
#ifdef O_SYNC
	O_RDONLY|O_CLOEXEC|O_PATH|O_SYNC,
#endif
#ifdef O_CLOEXEC
	O_RDONLY|O_LARGEFILE|O_CLOEXEC,
#endif
#ifdef O_NOATIME
	O_RDONLY|O_LARGEFILE|O_NOATIME,
#endif
#ifdef O_NOFOLLOW
	O_RDONLY|O_CLOEXEC|O_NOFOLLOW,
#endif
#ifdef O_NONBLOCK
	O_RDONLY|O_CLOEXEC|O_NONBLOCK,
#endif
#ifdef O_ASYNC
	O_RDONLY|O_CLOEXEC|O_PATH|O_ASYNC,
#endif
#ifdef O_DSYNC
	O_RDONLY|O_CLOEXEC|O_PATH|O_DSYNC,
#endif
#ifdef O_EXCL
	O_RDONLY|O_LARGEFILE|O_PATH|O_EXCL,
#endif
#ifdef O_SYNC
	O_RDONLY|O_LARGEFILE|O_PATH|O_SYNC,
#endif
#ifdef O_LARGEFILE
	O_RDONLY|O_CLOEXEC|O_LARGEFILE,
#endif
#ifdef O_NOFOLLOW
	O_RDONLY|O_LARGEFILE|O_NOFOLLOW,
#endif
#ifdef O_NONBLOCK
	O_RDONLY|O_LARGEFILE|O_NONBLOCK,
#endif
#ifdef O_APPEND
	O_RDONLY|O_CLOEXEC|O_PATH|O_APPEND,
#endif
#ifdef O_ASYNC
	O_RDONLY|O_LARGEFILE|O_PATH|O_ASYNC,
#endif
#ifdef O_DIRECT
	O_RDONLY|O_CLOEXEC|O_PATH|O_DIRECT,
#endif
#ifdef O_DSYNC
	O_RDONLY|O_LARGEFILE|O_PATH|O_DSYNC,
#endif
#ifdef O_NOCTTY
	O_RDONLY|O_CLOEXEC|O_PATH|O_NOCTTY,
#endif
#ifdef O_EXCL
	O_RDONLY|O_CLOEXEC|O_DIRECTORY|O_EXCL,
#endif
#ifdef O_LARGEFILE
	O_RDONLY|O_LARGEFILE|O_LARGEFILE,
#endif
#ifdef O_SYNC
	O_RDONLY|O_CLOEXEC|O_DIRECTORY|O_SYNC,
#endif
#ifdef O_APPEND
	O_RDONLY|O_LARGEFILE|O_PATH|O_APPEND,
#endif
#ifdef O_CLOEXEC
	O_RDONLY|O_CLOEXEC|O_PATH|O_CLOEXEC,
#endif
#ifdef O_DIRECT
	O_RDONLY|O_LARGEFILE|O_PATH|O_DIRECT,
#endif
#ifdef O_NOATIME
	O_RDONLY|O_CLOEXEC|O_PATH|O_NOATIME,
#endif
#ifdef O_NOCTTY
	O_RDONLY|O_LARGEFILE|O_PATH|O_NOCTTY,
#endif
#ifdef O_ASYNC
	O_RDONLY|O_CLOEXEC|O_DIRECTORY|O_ASYNC,
#endif
#ifdef O_DSYNC
	O_RDONLY|O_CLOEXEC|O_DIRECTORY|O_DSYNC,
#endif
#ifdef O_EXCL
	O_RDONLY|O_LARGEFILE|O_DIRECTORY|O_EXCL,
#endif
#ifdef O_SYNC
	O_RDONLY|O_LARGEFILE|O_DIRECTORY|O_SYNC,
#endif
#ifdef O_CLOEXEC
	O_RDONLY|O_LARGEFILE|O_PATH|O_CLOEXEC,
#endif
#ifdef O_NOATIME
	O_RDONLY|O_LARGEFILE|O_PATH|O_NOATIME,
#endif
#ifdef O_NOFOLLOW
	O_RDONLY|O_CLOEXEC|O_PATH|O_NOFOLLOW,
#endif
#ifdef O_NONBLOCK
	O_RDONLY|O_CLOEXEC|O_PATH|O_NONBLOCK,
#endif
#ifdef O_APPEND
	O_RDONLY|O_CLOEXEC|O_DIRECTORY|O_APPEND,
#endif
#ifdef O_ASYNC
	O_RDONLY|O_LARGEFILE|O_DIRECTORY|O_ASYNC,
#endif
#ifdef O_DIRECT
	O_RDONLY|O_CLOEXEC|O_DIRECTORY|O_DIRECT,
#endif
#ifdef O_DSYNC
	O_RDONLY|O_LARGEFILE|O_DIRECTORY|O_DSYNC,
#endif
#ifdef O_NOCTTY
	O_RDONLY|O_CLOEXEC|O_DIRECTORY|O_NOCTTY,
#endif
#ifdef O_LARGEFILE
	O_RDONLY|O_CLOEXEC|O_PATH|O_LARGEFILE,
#endif
#ifdef O_NOFOLLOW
	O_RDONLY|O_LARGEFILE|O_PATH|O_NOFOLLOW,
#endif
#ifdef O_NONBLOCK
	O_RDONLY|O_LARGEFILE|O_PATH|O_NONBLOCK,
#endif
#ifdef O_APPEND
	O_RDONLY|O_LARGEFILE|O_DIRECTORY|O_APPEND,
#endif
#ifdef O_CLOEXEC
	O_RDONLY|O_CLOEXEC|O_DIRECTORY|O_CLOEXEC,
#endif
#ifdef O_DIRECT
	O_RDONLY|O_LARGEFILE|O_DIRECTORY|O_DIRECT,
#endif
#ifdef O_NOATIME
	O_RDONLY|O_CLOEXEC|O_DIRECTORY|O_NOATIME,
#endif
#ifdef O_NOCTTY
	O_RDONLY|O_LARGEFILE|O_DIRECTORY|O_NOCTTY,
#endif
#ifdef O_LARGEFILE
	O_RDONLY|O_LARGEFILE|O_PATH|O_LARGEFILE,
#endif
#ifdef O_CLOEXEC
	O_RDONLY|O_LARGEFILE|O_DIRECTORY|O_CLOEXEC,
#endif
#ifdef O_NOATIME
	O_RDONLY|O_LARGEFILE|O_DIRECTORY|O_NOATIME,
#endif
#ifdef O_NOFOLLOW
	O_RDONLY|O_CLOEXEC|O_DIRECTORY|O_NOFOLLOW,
#endif
#ifdef O_NONBLOCK
	O_RDONLY|O_CLOEXEC|O_DIRECTORY|O_NONBLOCK,
#endif
#ifdef O_LARGEFILE
	O_RDONLY|O_CLOEXEC|O_DIRECTORY|O_LARGEFILE,
#endif
#ifdef O_NOFOLLOW
	O_RDONLY|O_LARGEFILE|O_DIRECTORY|O_NOFOLLOW,
#endif
#ifdef O_NONBLOCK
	O_RDONLY|O_LARGEFILE|O_DIRECTORY|O_NONBLOCK,
#endif
#ifdef O_LARGEFILE
	O_RDONLY|O_LARGEFILE|O_DIRECTORY|O_LARGEFILE,
#endif
};

#endif

